### ISSUE TITLE
Question on Go version

### ISSUE THREAD

**Issue by rangerrkm** [Adikso/minecraft-log4j-honeypot#3]
Hello,

I'm getting this error on Ubuntu 20.04 with Go version go1.13.8 linux/amd64.

cannot load embed: malformed module path "embed": missing dot in first path element

Do I need to use another Go version?

Any ideas as to what is causing this error.

Thanks,

**Comment by Adikso** [comment]
Hi, you should install at least Go 1.16

**Comment by Adikso** [comment]
1.16*

**Comment by Adikso** [comment]
You can also run it in docker container

**Comment by rangerrkm** [comment]
Yes, that is what I ended up doing, but wanted to use the other version to possibly change the port to a few others that I know they are attacking as of now.

Thanks for making this HoneyPot and the quick response.

**Comment by rangerrkm** [comment]
> Hi, you should install at least Go 1.16

I will try this one now.

I just apt just install the 1.13.

Thanks,

**Comment by Adikso** [comment]
You can run honeypot on docker with different port like that:
```
docker run --rm -it --mount type=bind,source="${PWD}/payloads",target=/payloads --user=`id -u` -p 2137:2137 adikso/minecraft-log4j-honeypot:latest -h ":2137"
```

**Comment by rangerrkm** [comment]
Yes, going to this version worked perfectly:
go version go1.16.12 linux/amd64

Thanks again Adikso
